import express, { type Express } from "express";
import fs from "fs";
import { type Server } from "http";
import { nanoid } from "nanoid";
import path from "path";
import { createServer as createViteServer } from "vite";
import viteConfig from "../../vite.config";

export async function setupVite(app: Express, server: Server) {
  const serverOptions = {
    middlewareMode: true,
    hmr: { server },
    allowedHosts: true as const,
  };

  const vite = await createViteServer({
    ...viteConfig,
    configFile: false,
    server: serverOptions,
    appType: "custom",
  });

  app.use(vite.middlewares);
  app.use("*", async (req, res, next) => {
    const url = req.originalUrl;

    try {
      const clientTemplate = path.resolve(
        import.meta.dirname,
        "../..",
        "client",
        "index.html"
      );

      // always reload the index.html file from disk incase it changes
      let template = await fs.promises.readFile(clientTemplate, "utf-8");
      template = template.replace(
        `src="/src/main.tsx"`,
        `src="/src/main.tsx?v=${nanoid()}"`
      );
      const page = await vite.transformIndexHtml(url, template);
      res.status(200).set({ "Content-Type": "text/html" }).end(page);
    } catch (e) {
      vite.ssrFixStacktrace(e as Error);
      next(e);
    }
  });
}

export function serveStatic(app: Express) {
  const distPath =
    process.env.NODE_ENV === "development"
      ? path.resolve(import.meta.dirname, "../..", "dist", "public")
      : path.resolve(import.meta.dirname, "public");
  if (!fs.existsSync(distPath)) {
    console.error(
      `Could not find the build directory: ${distPath}, make sure to build the client first`
    );
  }

  // IL-01: Serve prerendered HTML for /denver-homes-for-sale before express.static.
  // Must be registered BEFORE app.use(express.static(...)) to prevent express.static
  // from redirecting /denver-homes-for-sale → /denver-homes-for-sale/ (which hits SPA fallback).
  //
  // IL-01 path resolution strategy:
  // - Primary: server/prerendered/denver-homes-for-sale.html — committed to git, always present
  //   in production. Resolved via process.cwd() which is the project root at runtime.
  // - Fallback: dist/prerendered/denver-homes-for-sale.html — generated by pnpm build prerender
  //   step. Only present if the build step ran successfully (not gitignored but may be absent).
  //
  // This is a one-route PoC. Do not expand without an explicit patch plan.
  app.get("/denver-homes-for-sale", (_req, res) => {
    // Committed source file (always present in git checkout / production deploy)
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/denver-homes-for-sale.html");
    // Build-generated file (present after pnpm build runs prerender step)
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/denver-homes-for-sale.html");
    // Prefer the build-generated file if it exists (fresher), otherwise use committed source
    const prerendered = fs.existsSync(distPrerendered) ? distPrerendered : srcPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });

  // IL-02: Serve prerendered HTML for /colorado-springs-co-homes-for-sale before express.static.
  // Identical dual-path resolution pattern as IL-01 Denver handler.
  // Primary: server/prerendered/colorado-springs-co-homes-for-sale.html — committed to git.
  // Fallback: dist/prerendered/colorado-springs-co-homes-for-sale.html — build artifact.
  app.get("/colorado-springs-co-homes-for-sale", (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/colorado-springs-co-homes-for-sale.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/colorado-springs-co-homes-for-sale.html");
    const prerendered = fs.existsSync(distPrerendered) ? distPrerendered : srcPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });

  // IL-03: Serve prerendered HTML for /boulder-co-homes-for-sale before express.static.
  // Identical dual-path resolution pattern as IL-01 and IL-02 handlers.
  // Primary: server/prerendered/boulder-co-homes-for-sale.html — committed to git.
  // Fallback: dist/prerendered/boulder-co-homes-for-sale.html — build artifact.
  app.get("/boulder-co-homes-for-sale", (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/boulder-co-homes-for-sale.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/boulder-co-homes-for-sale.html");
    const prerendered = fs.existsSync(distPrerendered) ? distPrerendered : srcPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });

  // IL-04: Serve prerendered HTML for /black-forest-co-real-estate (+ trailing-slash form).
  // App.tsx registers this route with trailing slash, so both forms must be handled.
  // Primary: server/prerendered/black-forest-co-real-estate.html — committed to git.
  // Fallback: dist/prerendered/black-forest-co-real-estate.html — build artifact.
  app.get(["/black-forest-co-real-estate", "/black-forest-co-real-estate/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/black-forest-co-real-estate.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/black-forest-co-real-estate.html");
    const prerendered = fs.existsSync(distPrerendered) ? distPrerendered : srcPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });

  // IL-05: Serve prerendered HTML for /peyton-co-real-estate (+ trailing-slash form).
  // App.tsx registers this route with trailing slash, so both forms must be handled.
  // Primary: server/prerendered/peyton-co-real-estate.html — committed to git.
  // Fallback: dist/prerendered/peyton-co-real-estate.html — build artifact.
  app.get(["/peyton-co-real-estate", "/peyton-co-real-estate/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/peyton-co-real-estate.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/peyton-co-real-estate.html");
    const prerendered = fs.existsSync(distPrerendered) ? distPrerendered : srcPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });

  // IL-06: Serve prerendered HTML for /palmer-lake-co-real-estate (+ trailing-slash form).
  // App.tsx registers this route with trailing slash, so both forms must be handled.
  // Primary: server/prerendered/palmer-lake-co-real-estate.html — committed to git.
  // Fallback: dist/prerendered/palmer-lake-co-real-estate.html — build artifact.
  app.get(["/palmer-lake-co-real-estate", "/palmer-lake-co-real-estate/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/palmer-lake-co-real-estate.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/palmer-lake-co-real-estate.html");
    const prerendered = fs.existsSync(distPrerendered) ? distPrerendered : srcPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });

  // IL-07: Serve prerendered HTML for /parker-co-homes-for-sale (+ trailing-slash form).
  // Primary: server/prerendered/parker-co-homes-for-sale.html — committed to git.
  // Fallback: dist/prerendered/parker-co-homes-for-sale.html — build artifact.
  app.get(["/parker-co-homes-for-sale", "/parker-co-homes-for-sale/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/parker-co-homes-for-sale.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/parker-co-homes-for-sale.html");
    const prerendered = fs.existsSync(distPrerendered) ? distPrerendered : srcPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });

  // IL-08: Serve prerendered HTML for /highlands-ranch-co-homes-for-sale (+ trailing-slash form).
  // Primary: server/prerendered/highlands-ranch-co-homes-for-sale.html — committed to git.
  // Fallback: dist/prerendered/highlands-ranch-co-homes-for-sale.html — build artifact.
  app.get(["/highlands-ranch-co-homes-for-sale", "/highlands-ranch-co-homes-for-sale/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/highlands-ranch-co-homes-for-sale.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/highlands-ranch-co-homes-for-sale.html");
    const prerendered = fs.existsSync(distPrerendered) ? distPrerendered : srcPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });

  // IL-09: Serve prerendered HTML for /castle-rock-co-homes-for-sale (+ trailing-slash form).
  // Primary: server/prerendered/castle-rock-co-homes-for-sale.html — committed to git.
  // Fallback: dist/prerendered/castle-rock-co-homes-for-sale.html — build artifact.
  app.get(["/castle-rock-co-homes-for-sale", "/castle-rock-co-homes-for-sale/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/castle-rock-co-homes-for-sale.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/castle-rock-co-homes-for-sale.html");
    const prerendered = fs.existsSync(distPrerendered) ? distPrerendered : srcPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });

  // IL-10: Serve prerendered HTML for /littleton-co-homes-for-sale (+ trailing-slash form).
  // Primary: server/prerendered/littleton-co-homes-for-sale.html — committed to git.
  // Fallback: dist/prerendered/littleton-co-homes-for-sale.html — build artifact.
  app.get(["/littleton-co-homes-for-sale", "/littleton-co-homes-for-sale/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/littleton-co-homes-for-sale.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/littleton-co-homes-for-sale.html");
    const prerendered = fs.existsSync(distPrerendered) ? distPrerendered : srcPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });

  // IL-11: Serve prerendered HTML for /arvada-co-homes-for-sale (+ trailing-slash form).
  // Primary: server/prerendered/arvada-co-homes-for-sale.html — committed to git.
  // Fallback: dist/prerendered/arvada-co-homes-for-sale.html — build artifact.
  app.get(["/arvada-co-homes-for-sale", "/arvada-co-homes-for-sale/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/arvada-co-homes-for-sale.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/arvada-co-homes-for-sale.html");
    const prerendered = fs.existsSync(distPrerendered) ? distPrerendered : srcPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });

  // IL-12: Serve prerendered HTML for /fort-collins-co-homes-for-sale (+ trailing-slash form).
  // Primary: server/prerendered/fort-collins-co-homes-for-sale.html — committed to git.
  // Fallback: dist/prerendered/fort-collins-co-homes-for-sale.html — build artifact.
  app.get(["/fort-collins-co-homes-for-sale", "/fort-collins-co-homes-for-sale/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/fort-collins-co-homes-for-sale.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/fort-collins-co-homes-for-sale.html");
    const prerendered = fs.existsSync(srcPrerendered) ? srcPrerendered : distPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });

  // IL-13: Serve prerendered HTML for /loveland-co-homes-for-sale (+ trailing-slash form).
  // Primary: server/prerendered/loveland-co-homes-for-sale.html — committed to git.
  // Fallback: dist/prerendered/loveland-co-homes-for-sale.html — build artifact.
  app.get(["/loveland-co-homes-for-sale", "/loveland-co-homes-for-sale/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/loveland-co-homes-for-sale.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/loveland-co-homes-for-sale.html");
    const prerendered = fs.existsSync(srcPrerendered) ? srcPrerendered : distPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });

  // IL-14: Serve prerendered HTML for /windsor-co-homes-for-sale (+ trailing-slash form).
  // Primary: server/prerendered/windsor-co-homes-for-sale.html — committed to git.
  // Fallback: dist/prerendered/windsor-co-homes-for-sale.html — build artifact.
  app.get(["/windsor-co-homes-for-sale", "/windsor-co-homes-for-sale/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/windsor-co-homes-for-sale.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/windsor-co-homes-for-sale.html");
    const prerendered = fs.existsSync(srcPrerendered) ? srcPrerendered : distPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });

  // IL-15: Serve prerendered HTML for /johnstown-co-homes-for-sale (+ trailing-slash form).
  // Primary: server/prerendered/johnstown-co-homes-for-sale.html — committed to git.
  // Fallback: dist/prerendered/johnstown-co-homes-for-sale.html — build artifact.
  app.get(["/johnstown-co-homes-for-sale", "/johnstown-co-homes-for-sale/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/johnstown-co-homes-for-sale.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/johnstown-co-homes-for-sale.html");
    const prerendered = fs.existsSync(srcPrerendered) ? srcPrerendered : distPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });

  // IL-16: Serve prerendered HTML for /greeley-co-homes-for-sale (+ trailing-slash form).
  // Primary: server/prerendered/greeley-co-homes-for-sale.html — committed to git.
  // Fallback: dist/prerendered/greeley-co-homes-for-sale.html — build artifact.
  app.get(["/greeley-co-homes-for-sale", "/greeley-co-homes-for-sale/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/greeley-co-homes-for-sale.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/greeley-co-homes-for-sale.html");
    const prerendered = fs.existsSync(srcPrerendered) ? srcPrerendered : distPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });

  // IL-17: Serve prerendered HTML for /douglas-co-homes-for-sale (+ trailing-slash form).
  // Primary: server/prerendered/douglas-co-homes-for-sale.html — committed to git.
  // Fallback: dist/prerendered/douglas-co-homes-for-sale.html — build artifact.
  app.get(["/douglas-co-homes-for-sale", "/douglas-co-homes-for-sale/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/douglas-co-homes-for-sale.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/douglas-co-homes-for-sale.html");
    const prerendered = fs.existsSync(srcPrerendered) ? srcPrerendered : distPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });

  // IL-18: Serve prerendered HTML for /castle-pines-co-homes-for-sale (+ trailing-slash form).
  // Primary: server/prerendered/castle-pines-co-homes-for-sale.html — committed to git.
  // Fallback: dist/prerendered/castle-pines-co-homes-for-sale.html — build artifact.
  app.get(["/castle-pines-co-homes-for-sale", "/castle-pines-co-homes-for-sale/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/castle-pines-co-homes-for-sale.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/castle-pines-co-homes-for-sale.html");
    const prerendered = fs.existsSync(srcPrerendered) ? srcPrerendered : distPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });

  // IL-19: Serve prerendered HTML for /centennial-co-homes-for-sale (+ trailing-slash form).
  // Primary: server/prerendered/centennial-co-homes-for-sale.html — committed to git.
  // Fallback: dist/prerendered/centennial-co-homes-for-sale.html — build artifact.
  app.get(["/centennial-co-homes-for-sale", "/centennial-co-homes-for-sale/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/centennial-co-homes-for-sale.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/centennial-co-homes-for-sale.html");
    const prerendered = fs.existsSync(srcPrerendered) ? srcPrerendered : distPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });

  // IL-20: Serve prerendered HTML for /lone-tree-co-homes-for-sale (+ trailing-slash form).
  // Primary: server/prerendered/lone-tree-co-homes-for-sale.html — committed to git.
  // Fallback: dist/prerendered/lone-tree-co-homes-for-sale.html — build artifact.
  app.get(["/lone-tree-co-homes-for-sale", "/lone-tree-co-homes-for-sale/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/lone-tree-co-homes-for-sale.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/lone-tree-co-homes-for-sale.html");
    const prerendered = fs.existsSync(srcPrerendered) ? srcPrerendered : distPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });

  // IL-21: Serve prerendered HTML for /westminster-co-homes-for-sale (+ trailing-slash form).
  // Primary: server/prerendered/westminster-co-homes-for-sale.html — committed to git.
  // Fallback: dist/prerendered/westminster-co-homes-for-sale.html — build artifact.
  app.get(["/westminster-co-homes-for-sale", "/westminster-co-homes-for-sale/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/westminster-co-homes-for-sale.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/westminster-co-homes-for-sale.html");
    const prerendered = fs.existsSync(srcPrerendered) ? srcPrerendered : distPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });

  // IL-22: Serve prerendered HTML for /monument-co-real-estate (+ trailing-slash form).
  // Primary: server/prerendered/monument-co-real-estate.html — committed to git.
  // Fallback: dist/prerendered/monument-co-real-estate.html — build artifact.
  app.get(["/monument-co-real-estate", "/monument-co-real-estate/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/monument-co-real-estate.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/monument-co-real-estate.html");
    const prerendered = fs.existsSync(srcPrerendered) ? srcPrerendered : distPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });

  // IL-23: Serve prerendered HTML for /falcon-co-real-estate (+ trailing-slash form).
  // Primary: server/prerendered/falcon-co-real-estate.html — committed to git.
  // Fallback: dist/prerendered/falcon-co-real-estate.html — build artifact.
  app.get(["/falcon-co-real-estate", "/falcon-co-real-estate/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/falcon-co-real-estate.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/falcon-co-real-estate.html");
    const prerendered = fs.existsSync(srcPrerendered) ? srcPrerendered : distPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });

  // IL-24: Serve prerendered HTML for /fountain-co-real-estate (+ trailing-slash form).
  // Primary: server/prerendered/fountain-co-real-estate.html — committed to git.
  // Fallback: dist/prerendered/fountain-co-real-estate.html — build artifact.
  app.get(["/fountain-co-real-estate", "/fountain-co-real-estate/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/fountain-co-real-estate.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/fountain-co-real-estate.html");
    const prerendered = fs.existsSync(srcPrerendered) ? srcPrerendered : distPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });

  // IL-25: Serve prerendered HTML for /woodland-park-co-real-estate (+ trailing-slash form).
  // Primary: server/prerendered/woodland-park-co-real-estate.html — committed to git.
  // Fallback: dist/prerendered/woodland-park-co-real-estate.html — build artifact.
  app.get(["/woodland-park-co-real-estate", "/woodland-park-co-real-estate/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/woodland-park-co-real-estate.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/woodland-park-co-real-estate.html");
    const prerendered = fs.existsSync(srcPrerendered) ? srcPrerendered : distPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });

  // IL-26: Serve prerendered HTML for /manitou-springs-co-real-estate (+ trailing-slash form).
  // Primary: server/prerendered/manitou-springs-co-real-estate.html — committed to git.
  // Fallback: dist/prerendered/manitou-springs-co-real-estate.html — build artifact.
  app.get(["/manitou-springs-co-real-estate", "/manitou-springs-co-real-estate/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/manitou-springs-co-real-estate.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/manitou-springs-co-real-estate.html");
    const prerendered = fs.existsSync(srcPrerendered) ? srcPrerendered : distPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });

  // IL-27: Serve prerendered HTML for /briargate-colorado-springs-real-estate (+ trailing-slash form).
  // Primary: server/prerendered/briargate-colorado-springs-real-estate.html — committed to git.
  // Fallback: dist/prerendered/briargate-colorado-springs-real-estate.html — build artifact.
  app.get(["/briargate-colorado-springs-real-estate", "/briargate-colorado-springs-real-estate/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/briargate-colorado-springs-real-estate.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/briargate-colorado-springs-real-estate.html");
    const prerendered = fs.existsSync(srcPrerendered) ? srcPrerendered : distPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });

  // IL-28: Serve prerendered HTML for /northgate-colorado-springs-real-estate (+ trailing-slash form).
  // Primary: server/prerendered/northgate-colorado-springs-real-estate.html — committed to git.
  // Fallback: dist/prerendered/northgate-colorado-springs-real-estate.html — build artifact.
  app.get(["/northgate-colorado-springs-real-estate", "/northgate-colorado-springs-real-estate/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/northgate-colorado-springs-real-estate.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/northgate-colorado-springs-real-estate.html");
    const prerendered = fs.existsSync(srcPrerendered) ? srcPrerendered : distPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });

  // IL-29: Serve prerendered HTML for /flying-horse-colorado-springs-real-estate (+ trailing-slash form).
  // Primary: server/prerendered/flying-horse-colorado-springs-real-estate.html — committed to git.
  // Fallback: dist/prerendered/flying-horse-colorado-springs-real-estate.html — build artifact.
  app.get(["/flying-horse-colorado-springs-real-estate", "/flying-horse-colorado-springs-real-estate/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/flying-horse-colorado-springs-real-estate.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/flying-horse-colorado-springs-real-estate.html");
    const prerendered = fs.existsSync(srcPrerendered) ? srcPrerendered : distPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });

  // IL-30: Serve prerendered HTML for /cordera-colorado-springs-real-estate (+ trailing-slash form).
  // Primary: server/prerendered/cordera-colorado-springs-real-estate.html — committed to git.
  // Fallback: dist/prerendered/cordera-colorado-springs-real-estate.html — build artifact.
  app.get(["/cordera-colorado-springs-real-estate", "/cordera-colorado-springs-real-estate/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/cordera-colorado-springs-real-estate.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/cordera-colorado-springs-real-estate.html");
    const prerendered = fs.existsSync(srcPrerendered) ? srcPrerendered : distPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });

  // IL-31: Serve prerendered HTML for /pine-creek-colorado-springs-real-estate (+ trailing-slash form).
  // Primary: server/prerendered/pine-creek-colorado-springs-real-estate.html — committed to git.
  // Fallback: dist/prerendered/pine-creek-colorado-springs-real-estate.html — build artifact.
  app.get(["/pine-creek-colorado-springs-real-estate", "/pine-creek-colorado-springs-real-estate/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/pine-creek-colorado-springs-real-estate.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/pine-creek-colorado-springs-real-estate.html");
    const prerendered = fs.existsSync(srcPrerendered) ? srcPrerendered : distPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });

  // IL-32: Serve prerendered HTML for /mountain-shadows-colorado-springs-real-estate (+ trailing-slash form).
  // Primary: server/prerendered/mountain-shadows-colorado-springs-real-estate.html — committed to git.
  // Fallback: dist/prerendered/mountain-shadows-colorado-springs-real-estate.html — build artifact.
  app.get(["/mountain-shadows-colorado-springs-real-estate", "/mountain-shadows-colorado-springs-real-estate/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/mountain-shadows-colorado-springs-real-estate.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/mountain-shadows-colorado-springs-real-estate.html");
    const prerendered = fs.existsSync(srcPrerendered) ? srcPrerendered : distPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });
  // IL-33: Serve prerendered HTML for /peregrine-colorado-springs-real-estate (+ trailing-slash form).
  // Primary: server/prerendered/peregrine-colorado-springs-real-estate.html — committed to git.
  // Fallback: dist/prerendered/peregrine-colorado-springs-real-estate.html — build artifact.
  app.get(["/peregrine-colorado-springs-real-estate", "/peregrine-colorado-springs-real-estate/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/peregrine-colorado-springs-real-estate.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/peregrine-colorado-springs-real-estate.html");
    const prerendered = fs.existsSync(srcPrerendered) ? srcPrerendered : distPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });
  // IL-34: Serve prerendered HTML for /old-colorado-city-colorado-springs-real-estate (+ trailing-slash form).
  // Primary: server/prerendered/old-colorado-city-colorado-springs-real-estate.html — committed to git.
  // Fallback: dist/prerendered/old-colorado-city-colorado-springs-real-estate.html — build artifact.
  app.get(["/old-colorado-city-colorado-springs-real-estate", "/old-colorado-city-colorado-springs-real-estate/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/old-colorado-city-colorado-springs-real-estate.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/old-colorado-city-colorado-springs-real-estate.html");
    const prerendered = fs.existsSync(srcPrerendered) ? srcPrerendered : distPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });
  // IL-35: Serve prerendered HTML for /old-north-end-colorado-springs-real-estate (+ trailing-slash form).
  // Primary: server/prerendered/old-north-end-colorado-springs-real-estate.html — committed to git.
  // Fallback: dist/prerendered/old-north-end-colorado-springs-real-estate.html — build artifact.
  app.get(["/old-north-end-colorado-springs-real-estate", "/old-north-end-colorado-springs-real-estate/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/old-north-end-colorado-springs-real-estate.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/old-north-end-colorado-springs-real-estate.html");
    const prerendered = fs.existsSync(srcPrerendered) ? srcPrerendered : distPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });
  // IL-36: Serve prerendered HTML for /broadmoor-cheyenne-mountain-colorado-springs-real-estate (+ trailing-slash form).
  // Primary: server/prerendered/broadmoor-cheyenne-mountain-colorado-springs-real-estate.html — committed to git.
  // Fallback: dist/prerendered/broadmoor-cheyenne-mountain-colorado-springs-real-estate.html — build artifact.
  app.get(["/broadmoor-cheyenne-mountain-colorado-springs-real-estate", "/broadmoor-cheyenne-mountain-colorado-springs-real-estate/"], (_req, res) => {
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/broadmoor-cheyenne-mountain-colorado-springs-real-estate.html");
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/broadmoor-cheyenne-mountain-colorado-springs-real-estate.html");
    const prerendered = fs.existsSync(srcPrerendered) ? srcPrerendered : distPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });
  app.use(express.static(distPath));

  // fall through to index.html if the file doesn't exist
  app.use("*", (_req, res) => {
    res.sendFile(path.resolve(distPath, "index.html"));
  });
}
