import express, { type Express } from "express";
import fs from "fs";
import { type Server } from "http";
import { nanoid } from "nanoid";
import path from "path";
import { createServer as createViteServer } from "vite";
import viteConfig from "../../vite.config";

export async function setupVite(app: Express, server: Server) {
  const serverOptions = {
    middlewareMode: true,
    hmr: { server },
    allowedHosts: true as const,
  };

  const vite = await createViteServer({
    ...viteConfig,
    configFile: false,
    server: serverOptions,
    appType: "custom",
  });

  app.use(vite.middlewares);
  app.use("*", async (req, res, next) => {
    const url = req.originalUrl;

    try {
      const clientTemplate = path.resolve(
        import.meta.dirname,
        "../..",
        "client",
        "index.html"
      );

      // always reload the index.html file from disk incase it changes
      let template = await fs.promises.readFile(clientTemplate, "utf-8");
      template = template.replace(
        `src="/src/main.tsx"`,
        `src="/src/main.tsx?v=${nanoid()}"`
      );
      const page = await vite.transformIndexHtml(url, template);
      res.status(200).set({ "Content-Type": "text/html" }).end(page);
    } catch (e) {
      vite.ssrFixStacktrace(e as Error);
      next(e);
    }
  });
}

export function serveStatic(app: Express) {
  const distPath =
    process.env.NODE_ENV === "development"
      ? path.resolve(import.meta.dirname, "../..", "dist", "public")
      : path.resolve(import.meta.dirname, "public");
  if (!fs.existsSync(distPath)) {
    console.error(
      `Could not find the build directory: ${distPath}, make sure to build the client first`
    );
  }

  // IL-01: Serve prerendered HTML for /denver-homes-for-sale before express.static.
  // Must be registered BEFORE app.use(express.static(...)) to prevent express.static
  // from redirecting /denver-homes-for-sale → /denver-homes-for-sale/ (which hits SPA fallback).
  //
  // IL-01 path resolution strategy:
  // - Primary: server/prerendered/denver-homes-for-sale.html — committed to git, always present
  //   in production. Resolved via process.cwd() which is the project root at runtime.
  // - Fallback: dist/prerendered/denver-homes-for-sale.html — generated by pnpm build prerender
  //   step. Only present if the build step ran successfully (not gitignored but may be absent).
  //
  // This is a one-route PoC. Do not expand without an explicit patch plan.
  app.get("/denver-homes-for-sale", (_req, res) => {
    // Committed source file (always present in git checkout / production deploy)
    const srcPrerendered = path.resolve(process.cwd(), "server/prerendered/denver-homes-for-sale.html");
    // Build-generated file (present after pnpm build runs prerender step)
    const distPrerendered = path.resolve(import.meta.dirname, "prerendered/denver-homes-for-sale.html");
    // Prefer the build-generated file if it exists (fresher), otherwise use committed source
    const prerendered = fs.existsSync(distPrerendered) ? distPrerendered : srcPrerendered;
    if (fs.existsSync(prerendered)) {
      res.sendFile(prerendered);
    } else {
      res.sendFile(path.resolve(distPath, "index.html"));
    }
  });

  app.use(express.static(distPath));

  // fall through to index.html if the file doesn't exist
  app.use("*", (_req, res) => {
    res.sendFile(path.resolve(distPath, "index.html"));
  });
}
